# Generated by Django 5.1.5 on 2025-02-03 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from ..models import seed_cities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('places', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races_from', to='ApiCore.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races_to', to='ApiCore.city')),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCore.passenger')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCore.race')),
            ],
            options={
                'db_table': 'tickets',
                'constraints': [models.UniqueConstraint(fields=('passenger', 'race'), name='passenger_race_unique')],
            },
        ),
        migrations.RunPython(seed_cities)
    ]
