# Generated by Django 5.1.5 on 2025-02-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiCore.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiCore.race'),
        ),
    ]
